# Generated by Django 4.2.13 on 2024-07-05 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_]+$'), django.core.validators.MinLengthValidator(3)])),
                ('msgText', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
